#ddev-generated

log:
  level: DEBUG
accesslog: { }

api:
  dashboard: true
  insecure: true

core:
  defaultRuleSyntax: v2

certificatesResolvers:
  acme-tlsChallenge:
    acme:
      email: {{ .LetsEncryptEmail }}
      # To avoid Let's Encrypt rate-limiting, remove the ddev-generated line at top
      # and uncomment `caServer` here to use the staging caServer and avoid messages like
      # rateLimited :: Error creating new order :: too many failed authorizations recently:
      # see https://letsencrypt.org/docs/failed-validation-limit/
      #caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      storage: /mnt/ddev-global-cache/traefik/acme.json
      tlsChallenge: {}

providers:
  file:
    directory: /mnt/ddev-global-cache/traefik/config
    watch: true
global:
  sendanonymoususage: false

ping:
  entryPoint: "traefik"

entryPoints:
  traefik:
    address: ":{{.TraefikMonitorPort}}"
  {{ range $port := .RouterPorts }}
  http-{{$port}}:
    address: ":{{ $port }}"
  {{ end }}
