blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ DDEV Community Discord
    url: https://ddev.com/s/discord
    about: Join the DDEV Community to talk, exchange experiences or ask and answer questions.

