name: Static Validation

on:
  push:
    tags:
      - v*
    branches: [ main, master ]
  pull_request:
    paths:
      - ".github/workflows/**"
      - "!.github/workflows/docs**"
      - "cmd/**"
      - "pkg/**"
      - "go.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read

jobs:
  lint:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for golangci/golangci-lint-action to fetch pull requests
    name: Lint Go Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '>=1.23'
          check-latest: true

      - name: Add Homebrew to PATH
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

      - name: Lint Go Files
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.2.1
          args: --config=.golangci.yml

  check_modules:
    name: Check Go Modules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '>=1.23'
          check-latest: true

      # Fails if something is wrong with the dependencies
      - name: Verify Go Modules
        run: |
          go mod verify

      # Fails if modules aren't in a clean state
      - name: Tidy Go Modules
        run: |
          go mod tidy
          git diff --exit-code
