name: Test Podman Rootless Mutagen
on:
#  pull_request:
#    paths:
#      - "go.*"
#      - "pkg/**"
#      - "cmd/**"
#      - "Makefile"
#      - "vendor/**"
#      - ".github/workflows/**"
#      - "!.github/workflows/docs**"
  push:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate set "debug_enabled"'
        type: boolean
        required: false
        default: false
      ddev_embargo_tests:
        description: 'Comma-separated list of test names to skip'
        type: string
        required: false
        default: ''

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  podman-rootless-mutagen-testpkg-1:
    uses: ./.github/workflows/test-reusable.yml
    secrets: inherit
    with:
      make_target: "testpkg"
      testargs: "-failfast -run ^Test[A-G]"
      ddev_test_podman_rootless: "true"
      ddev_test_use_mutagen: "true"
      ddev_embargo_tests: ${{ inputs.ddev_embargo_tests || '' }}
      debug_enabled: ${{ inputs.debug_enabled || false }}

  podman-rootless-mutagen-testpkg-2:
    uses: ./.github/workflows/test-reusable.yml
    secrets: inherit
    with:
      make_target: "testpkg"
      testargs: "-failfast -run ^Test[H-Z]"
      ddev_test_podman_rootless: "true"
      ddev_test_use_mutagen: "true"
      ddev_embargo_tests: ${{ inputs.ddev_embargo_tests || '' }}
      debug_enabled: ${{ inputs.debug_enabled || false }}

  podman-rootless-mutagen-testcmd:
    uses: ./.github/workflows/test-reusable.yml
    secrets: inherit
    with:
      make_target: "testcmd"
      ddev_test_podman_rootless: "true"
      ddev_test_use_mutagen: "true"
      ddev_embargo_tests: ${{ inputs.ddev_embargo_tests || '' }}
      debug_enabled: ${{ inputs.debug_enabled || false }}
